### PR TITLE
Add CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by preronagit**
CODE_OF_CONDUCT.md file added which contains necessary guidelines for the contributors.

### CODE REVIEW

**Comment by preronagit** [comment]
It fixes issue #1.

**Comment by Abiji-2020** [comment]
It would be nice if the discord mention of the hacktoberfest server should
be removed as, the head repository of the Minds-go-sdk is not
hacktoberfest.
*Regards *
*Abinand*

**Comment by preronagit** [comment]
@Abiji-2020 Can you please share a contact address of Minds-go-sdk so that I can add it in the code of conduct?

**Comment by Abiji-2020** [comment]
Currently we dont have a discord server, you can mention the github handle (
https://github.com/Abiji-2020) and the email address ***@***.***"
*Regards *
*Abinand*

**Comment by preronagit** [comment]
@Abiji-2020 I have updated the CODE_OF_CONDUCT.md file.

**Pull request merged**
